/bin/rm -dfR ./mysql/data/*
/bin/rm -dfR ./phpmyadmin/sessions/*
#/bin/rm -dfR ./wordpress/plugins/*
/bin/rm -dfR ./wordpress/plugins/akismet
/bin/rm -dfR ./wordpress/plugins/hello.php
/bin/rm -dfR ./wordpress/plugins/index.php
#/bin/rm -dfR ./wordpress/themes/*
/bin/rm -dfR ./wordpress/themes/index.php
/bin/rm -dfR ./wordpress/themes/twentyfifteen
/bin/rm -dfR ./wordpress/themes/twentyseventeen
/bin/rm -dfR ./wordpress/themes/twentysixteen